version: '3'
services:
  mftf:
    image: magestore/mftf:2.2.6-apache-php7.1
    volumes:
      - ./app/code:/var/www/html/app/code
      # - ./app/pub/apps:/var/www/html/pub/apps
      - ./app/allure/allure-results:/allure-results
      - ./app/.composer:/var/www/.composer
    environment:
      BASE_URL: https://localhost.com/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  selenium:
    build: ./selenium
    image: selenium:1.0
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    networks:
      - webnet

  db:
    image: magestore/mftf-db:2.2.6
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

networks:
  webnet:
