version: '3'
services:
  mftf:
    build: ./mftf
    image: mftf:1.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app/code:/var/www/html/app/code
      - ./app/tests:/var/www/html/tests
    environment:
      BASE_URL: https://localhost.com/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  selenium:
    build: ./selenium
    image: selenium:1.0
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - webnet

  db:
    build: ./db
    image: db:1.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

networks:
  webnet:
