version: '3'
services:
  mftf:
    image: davidmagestore/mftf:2.2.4
    volumes:
      - ./app/code:/var/www/html/app/code
      # - ./app/pub/apps:/var/www/html/pub/apps
    environment:
      BASE_URL: https://localhost.com/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  selenium:
    image: davidmagestore/mftf-selenium-chrome
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    networks:
      - webnet

  db:
    image: davidmagestore/mftf-db:2.2.4
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

networks:
  webnet:
