version: '3'
services:
  selenium:
    build: ./selenium
    image: selenium:1.0
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm

  mftf:
    build: ./mftf
    image: mftf:1.0
    ports:
      - 80:80
      - 443:443

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
