version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm

  mftf:
    build: ./mftf
    image: mftf:1.0

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
