version: '3'
services:
  mftf:
    build: ./mftf
    image: mftf:1.0
    volumes:
      - ./app/code:/var/www/html/app/code
      # - ./app/pub/apps:/var/www/html/pub/apps
      - ./app/allure/allure-results:/allure-results
      - ./app/.composer:/var/www/.composer
    environment:
      BASE_URL: https://localhost.com/
      MAGENTO_DEV_MODE: developer
    networks:
      webnet:
        aliases:
          - localhost.com

  selenium:
    build: ./selenium
    image: selenium:1.0
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - webnet

  mailhog:
    image: mailhog/mailhog
    networks:
      - webnet

  db:
    build: ./db
    image: db:1.0
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet

  allure:
    build: ./allure
    image: allure:1.0
    volumes:
      - ./app/allure/allure-results:/allure-results
      - ./app/allure/allure-report:/allure-report
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./app/allure/allure-report:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
